[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "stillpoint-bar"
version = "0.1.1"
description = "A calm, typographically considered progress indicator for the terminal."
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
authors = [
    { name = "Abhishek Shah", email = "abhishek.aimarine@gmail.com" }
]
keywords = ["progress-bar", "cli", "terminal", "ui", "design", "ambient"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: User Interfaces",
    "Topic :: Terminals",
]
dependencies = []

[project.urls]
Homepage = "https://abhishekshah.vercel.app"
Repository = "https://github.com/abhiverse01/stillpoint"

[tool.setuptools.packages.find]
where = ["src"]
